# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.9/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.9/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/juanitahowe/Documents/GitHub/complier

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/juanitahowe/Documents/GitHub/complier

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.9/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.9/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/juanitahowe/Documents/GitHub/complier/CMakeFiles /Users/juanitahowe/Documents/GitHub/complier//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/juanitahowe/Documents/GitHub/complier/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tinyCompiler

# Build rule for target.
tinyCompiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tinyCompiler
.PHONY : tinyCompiler

# fast build rule for target.
tinyCompiler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyCompiler.dir/build.make CMakeFiles/tinyCompiler.dir/build
.PHONY : tinyCompiler/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named tinycompiler_clean

# Build rule for target.
tinycompiler_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tinycompiler_clean
.PHONY : tinycompiler_clean

# fast build rule for target.
tinycompiler_clean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinycompiler_clean.dir/build.make CMakeFiles/tinycompiler_clean.dir/build
.PHONY : tinycompiler_clean/fast

lex.yy.o: lex.yy.cpp.o
.PHONY : lex.yy.o

# target to build an object file
lex.yy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyCompiler.dir/build.make CMakeFiles/tinyCompiler.dir/lex.yy.cpp.o
.PHONY : lex.yy.cpp.o

lex.yy.i: lex.yy.cpp.i
.PHONY : lex.yy.i

# target to preprocess a source file
lex.yy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyCompiler.dir/build.make CMakeFiles/tinyCompiler.dir/lex.yy.cpp.i
.PHONY : lex.yy.cpp.i

lex.yy.s: lex.yy.cpp.s
.PHONY : lex.yy.s

# target to generate assembly for a file
lex.yy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyCompiler.dir/build.make CMakeFiles/tinyCompiler.dir/lex.yy.cpp.s
.PHONY : lex.yy.cpp.s

sign_table.o: sign_table.cpp.o
.PHONY : sign_table.o

# target to build an object file
sign_table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyCompiler.dir/build.make CMakeFiles/tinyCompiler.dir/sign_table.cpp.o
.PHONY : sign_table.cpp.o

sign_table.i: sign_table.cpp.i
.PHONY : sign_table.i

# target to preprocess a source file
sign_table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyCompiler.dir/build.make CMakeFiles/tinyCompiler.dir/sign_table.cpp.i
.PHONY : sign_table.cpp.i

sign_table.s: sign_table.cpp.s
.PHONY : sign_table.s

# target to generate assembly for a file
sign_table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyCompiler.dir/build.make CMakeFiles/tinyCompiler.dir/sign_table.cpp.s
.PHONY : sign_table.cpp.s

y.tab.o: y.tab.cpp.o
.PHONY : y.tab.o

# target to build an object file
y.tab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyCompiler.dir/build.make CMakeFiles/tinyCompiler.dir/y.tab.cpp.o
.PHONY : y.tab.cpp.o

y.tab.i: y.tab.cpp.i
.PHONY : y.tab.i

# target to preprocess a source file
y.tab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyCompiler.dir/build.make CMakeFiles/tinyCompiler.dir/y.tab.cpp.i
.PHONY : y.tab.cpp.i

y.tab.s: y.tab.cpp.s
.PHONY : y.tab.s

# target to generate assembly for a file
y.tab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyCompiler.dir/build.make CMakeFiles/tinyCompiler.dir/y.tab.cpp.s
.PHONY : y.tab.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... tinycompiler_clean"
	@echo "... tinyCompiler"
	@echo "... lex.yy.o"
	@echo "... lex.yy.i"
	@echo "... lex.yy.s"
	@echo "... sign_table.o"
	@echo "... sign_table.i"
	@echo "... sign_table.s"
	@echo "... y.tab.o"
	@echo "... y.tab.i"
	@echo "... y.tab.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

